# Solutions to Question 5 in the Diagnostic Quiz for
# "The Mathematical Engineering of Deep Learning"

See [deeplearningmath.org](https://deeplearningmath.org)

### 5a: Given an input matrix, check if it is: Symmetric, upper-triangular, lower-triangular.

In [28]:
"""
Check if an input matrix is:
* Symmetric
* Upper-triangular
* Lower-traingular

Returns an array of symbols including `:notSquare`,
`:symmetric`, `:lowerTriangular`, `:upperTriangular`

"""
function checkMatrix(matrix::Array{T,2}) where T<:Number
    n, m = size(matrix)
    n != m && return [:notSquare]
    
    symmetricFlag, lowerTriangularFlag, upperTriangularFlag = true, true, true
    
    for i in 2:n
        for j in 2:i-1
            symmetricFlag &= matrix[i,j] == matrix[j,i]
            lowerTriangularFlag &= matrix[i,j] == 0
            upperTriangularFlag &= matrix[j,i] == 0
        end
    end
    
    descriptors = []
    symmetricFlag && push!(descriptors,:symmetric) 
    lowerTriangularFlag && push!(descriptors,:lowerTriangular) 
    upperTriangularFlag && push!(descriptors,:upperTriangular) 
    return descriptors 
end

checkMatrix

In [2]:
? checkMatrix

search: checkMatrix



Check if an input matrix is:

  * Symmetric
  * Upper-triangular
  * Lower-traingular

Returns an array of symbols including `:notSquare`, `:symmetric`, `:lowerTriangular`, `:upperTriangular`


In [3]:
using Random
Random.seed!(0)
A = rand(1:5,4,4)
checkMatrix(A)

0-element Array{Any,1}

In [4]:
Random.seed!(0)
A = rand(1:5,4,5)
checkMatrix(A)

1-element Array{Symbol,1}:
 :notSquare

In [5]:
Random.seed!(0)
A = rand(1:5,4,4)
A = (A' + A)/2
checkMatrix(A)

1-element Array{Any,1}:
 :symmetric

In [6]:
Random.seed!(0)
A = rand(1:5,4,4)
for i in 2:4
    for j in 2:4-1
        A[i,j] = 0
    end
end
checkMatrix(A)

1-element Array{Any,1}:
 :lowerTriangular

In [7]:
Random.seed!(0)
A = rand(1:5,4,4)
for i in 2:4
    for j in 2:4-1
        A[j,i] = 0
    end
end
checkMatrix(A)

1-element Array{Any,1}:
 :upperTriangular

In [5]:
using LinearAlgebra
Random.seed!(0)
A = diagm(rand(1:5,4))
checkMatrix(A)

3-element Array{Any,1}:
 :symmetric
 :lowerTriangular
 :upperTriangular

### 5b) Given a list of numbers, return a sorted list of numbers.

In [29]:
"""
Sorts the input array according to the bubble sort algorithm. Sorts in place.
This is taken from ["Statistics with Julia"](https://statisticswithjulia.org/), Listing 1.6.
"""
function bubbleSort!(a::Array{T}) where T
    n = length(a)
    for i in 1:n-1
        for j in 1:n-i
            if a[j] > a[j+1]
                a[j], a[j+1] = a[j+1], a[j]
            end
        end
    end
    return a
end

bubbleSort!

In [30]:
? bubbleSort!

search: bubbleSort!



Sorts the input array according to the bubble sort algorithm. Sorts in place. This is taken from ["Statistics with Julia"](https://statisticswithjulia.org/), Listing 1.6.


In [9]:
using Random
Random.seed!(0)
data = rand(1:20,10)

10-element Array{Int64,1}:
  1
 19
 17
 11
  1
 20
 15
 12
  6
  8

In [10]:
bubbleSort!(data)

10-element Array{Int64,1}:
  1
  1
  6
  8
 11
 12
 15
 17
 19
 20

### 5c) Given a sequence of $n$ input vectors, each of length $p$, compute the $p\times p$ sample covariance matrix of these vectors.


In [75]:
"""

See also ["Statistics with Julia"](https://statisticswithjulia.org/), Listing 4.13.
"""
function myCov(dataArray::Array{Array{T,1},1}) where T <: Number
    n = length(dataArray)
    p = length(dataArray[1])
    sums = zeros(p)
    for x in dataArray
        sums += x
    end
    demeanedData = [x - sums/n for x in dataArray]
    cov = zeros(T,p,p)
    for x in demeanedData
        cov += x*x'
    end
    return cov/(n-1)
end

myCov

In [71]:
? myCov

search: myCov



See also ["Statistics with Julia"](https://statisticswithjulia.org/), Listing 4.13.

---

See also ["Statistics with Julia"](https://statisticswithjulia.org/), Listing 4.13.


In [77]:
using Random, Distributions, LinearAlgebra
Random.seed!(0)
μ = [10, 20, 30] #To enter a symbol like μ use \mu + [TAB]
Σ = [2 0.3 0.7;
     0.3 4 1.5;
     0.7 1.5 2.3]  #To enter a symbol like Σ use \Sigma + [TAB]
@show isposdef(Σ)
dist = MvNormal(μ,Σ)
N = 10^6
data = [rand(dist) for _ in 1:N]
myCov(data)

isposdef(Σ) = true


3×3 Array{Float64,2}:
 2.00118   0.303433  0.699163
 0.303433  4.00789   1.50352
 0.699163  1.50352   2.29857

### 5d) Use brute-force Riemann sums to illustrate numerically that 

$$
\int_{x_1 = -5}^5 \int_{x_2= -5}^5 ~\frac{1}{2 \pi}e^{-\frac{x_1^2 + x_2^2}{2}} ~ dx_1\, dx_2  \approx 1.
$$


In [25]:
δ = 0.01
sum([1/2π * exp(-(x₁^2 + x₂^2)/2) * δ^2 for x₁ in -5:δ:5, x₂ in -5:δ:5])

0.9999988828806374